/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sliding-hyper_TYPES_H
#define sliding-hyper_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class InternalError;

typedef struct _InternalError__isset {
  _InternalError__isset() : message(false) {}
  bool message :1;
} _InternalError__isset;

class InternalError : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  InternalError(const InternalError&);
  InternalError& operator=(const InternalError&);
  InternalError() : message() {
  }

  virtual ~InternalError() throw();
  std::string message;

  _InternalError__isset __isset;

  void __set_message(const std::string& val);

  bool operator == (const InternalError & rhs) const
  {
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const InternalError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InternalError & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const InternalError& obj);
};

void swap(InternalError &a, InternalError &b);



#endif
