/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sliding-hyper_constants.h"



const sliding-hyperConstants g_sliding-hyper_constants;

sliding-hyperConstants::sliding-hyperConstants() {
}



