/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sliding-hyper_CONSTANTS_H
#define sliding-hyper_CONSTANTS_H

#include "sliding-hyper_types.h"



class sliding-hyperConstants {
 public:
  sliding-hyperConstants();

};

extern const sliding-hyperConstants g_sliding-hyper_constants;



#endif
